export const WORD_BANK: Record<string, string[]> = {
  "Futbol": [
    "Messi", "Cristiano Ronaldo", "Pelé", "Maradona", "Neymar",
    "Mbappé", "Zidane", "Ronaldinho", "Beckham", "Ronaldo Nazário",
    "Buffon", "Casillas", "Ramos", "Piqué", "Modric",
    "Benzema", "Lewandowski", "Haaland", "De Bruyne", "Salah",
    "Hugo Sánchez", "Chicharito", "Rafa Márquez", "Cuauhtémoc Blanco", "Jorge Campos",
    "Xavi", "Iniesta", "Pirlo", "Totti", "Henry",
    "Drogba", "Eto'o", "Suárez", "Cavani", "Di María",
    "Vinícius Jr", "Bellingham", "Pedri", "Gavi", "Lamine Yamal",
    "Real Madrid", "Barcelona", "Manchester United", "Liverpool", "Bayern Munich",
    "PSG", "Juventus", "AC Milan", "Inter de Milán", "Chelsea",
    "América", "Chivas", "Tigres", "Monterrey", "Cruz Azul",
    "Boca Juniors", "River Plate", "Flamengo", "Santos", "Ajax",
    "Guardiola", "Mourinho", "Klopp", "Ancelotti", "Ferguson",
    "Champions League", "Copa del Mundo", "Liga MX", "Premier League", "La Liga",
    "Copa Libertadores", "Balón de Oro", "Copa América", "Eurocopa", "Mundialito",
    "Mano de Dios", "Chilena", "Tiki-taka", "VAR", "Penal a lo Panenka",
    "Fuera de lugar", "Hat-trick", "Gol olímpico", "Rabona", "Sombrero",
    "Tarjeta roja", "Tiempo extra", "Tanda de penales", "Descenso", "Derbi",
    "Santiago Bernabéu", "Camp Nou", "Wembley", "Maracaná", "Azteca",
    "Anfield", "San Siro", "Old Trafford", "Allianz Arena", "La Bombonera"
  ],
  "Futbol Americano": [
    "Tom Brady", "Patrick Mahomes", "Aaron Rodgers", "Peyton Manning", "Joe Montana",
    "Jerry Rice", "Lawrence Taylor", "Joe Burrow", "Lamar Jackson", "Josh Allen",
    "Travis Kelce", "Tyreek Hill", "Derrick Henry", "Jalen Hurts", "Dak Prescott",
    "Deion Sanders", "Ray Lewis", "Brett Favre", "Dan Marino", "John Elway",
    "Randy Moss", "Odell Beckham Jr", "Rob Gronkowski", "Tony Romo", "Russell Wilson",
    "Justin Jefferson", "CeeDee Lamb", "Micah Parsons", "T.J. Watt", "Myles Garrett",
    "Jim Brown", "Walter Payton", "Emmitt Smith", "Barry Sanders", "Bo Jackson",
    "Kansas City Chiefs", "Dallas Cowboys", "New England Patriots", "Green Bay Packers", "San Francisco 49ers",
    "Buffalo Bills", "Philadelphia Eagles", "Baltimore Ravens", "Miami Dolphins", "Pittsburgh Steelers",
    "Denver Broncos", "Las Vegas Raiders", "Chicago Bears", "New York Giants", "Seattle Seahawks",
    "Super Bowl", "Touchdown", "Hail Mary", "Quarterback sneak", "Blitz",
    "Pick six", "Safety", "Fumble", "Interceptación", "Two-point conversion",
    "Punt return", "Kickoff", "Field goal", "Draft", "Combine",
    "Playbook", "Shotgun", "Wildcat", "Hurry-up offense", "Prevent defense",
    "Halftime Show", "NFL Draft", "Monday Night Football", "Vince Lombardi Trophy", "Pro Bowl",
    "Madden NFL", "Fantasy Football", "Tailgate", "Cheerleaders", "Gatorade shower",
    "Lombardi", "Bill Belichick", "Andy Reid", "John Madden", "Al Michaels",
    "SoFi Stadium", "Lambeau Field", "AT&T Stadium", "Arrowhead Stadium", "MetLife Stadium"
  ],
  "Cine": [
    "Christopher Nolan", "Steven Spielberg", "Quentin Tarantino", "Martin Scorsese", "Stanley Kubrick",
    "Guillermo del Toro", "Alfonso Cuarón", "Denis Villeneuve", "Ridley Scott", "James Cameron",
    "Wes Anderson", "David Fincher", "Tim Burton", "Hayao Miyazaki", "Jordan Peele",
    "Greta Gerwig", "Alejandro González Iñárritu", "Coen Brothers", "Francis Ford Coppola", "Spike Lee",
    "Leonardo DiCaprio", "Cillian Murphy", "Margot Robbie", "Robert Downey Jr", "Meryl Streep",
    "Morgan Freeman", "Brad Pitt", "Keanu Reeves", "Scarlett Johansson", "Tom Hanks",
    "Al Pacino", "Robert De Niro", "Denzel Washington", "Natalie Portman", "Joaquin Phoenix",
    "Timothée Chalamet", "Zendaya", "Florence Pugh", "Pedro Pascal", "Austin Butler",
    "Jack Nicholson", "Samuel L. Jackson", "Will Smith", "Heath Ledger", "Cate Blanchett",
    "Anya Taylor-Joy", "Ana de Armas", "Ryan Gosling", "Jake Gyllenhaal", "Christian Bale",
    "Pulp Fiction", "The Godfather", "Inception", "Interstellar", "The Dark Knight",
    "Fight Club", "Forrest Gump", "The Shawshank Redemption", "Titanic", "The Matrix",
    "Oppenheimer", "Barbie", "Parasite", "Avengers Endgame", "Spider-Man No Way Home",
    "El laberinto del fauno", "Roma", "Coco", "Shrek", "Toy Story",
    "Star Wars", "Jurassic Park", "Back to the Future", "The Lion King", "Gladiator",
    "Jaws", "E.T.", "Alien", "Blade Runner", "John Wick",
    "Dune", "Top Gun Maverick", "Everything Everywhere All at Once", "Whiplash", "La La Land",
    "Oscar", "Cannes", "Globo de Oro", "Palma de Oro", "Sundance"
  ],
  "Animales": [
    "León", "Tigre", "Elefante", "Gorila", "Oso polar",
    "Lobo", "Zorro", "Delfín", "Ballena azul", "Orca",
    "Rinoceronte", "Hipopótamo", "Jirafa", "Cebra", "Canguro",
    "Koala", "Panda", "Orangután", "Chimpancé", "Jaguar",
    "Leopardo", "Guepardo", "Hiena", "Nutria", "Castor",
    "Mapache", "Murciélago", "Armadillo", "Oso hormiguero", "Perezoso",
    "Bisonte", "Alce", "Reno", "Cabra montés", "Suricata",
    "Lémur", "Foca", "Morsa", "Narval", "Beluga",
    "Águila calva", "Cóndor", "Tucán", "Guacamaya", "Búho",
    "Pingüino emperador", "Flamenco", "Colibrí", "Pavo real", "Halcón peregrino",
    "Pelícano", "Avestruz", "Kiwi", "Loro", "Cuervo",
    "Cocodrilo", "Camaleón", "Iguana", "Cobra real", "Anaconda",
    "Tortuga marina", "Dragón de Komodo", "Gecko", "Salamandra", "Axolote",
    "Boa constrictor", "Pitón", "Caimán", "Tortuga galápagos", "Lagarto cornudo",
    "Tiburón blanco", "Tiburón martillo", "Pulpo", "Mantarraya", "Medusa",
    "Pez payaso", "Caballito de mar", "Estrella de mar", "Cangrejo", "Langosta",
    "Calamar gigante", "Pez globo", "Barracuda", "Anguila eléctrica", "Coral",
    "Mariposa monarca", "Escorpión", "Tarántula", "Libélula", "Escarabajo",
    "Mantis religiosa", "Luciérnaga", "Avispa", "Hormiga roja", "Viuda negra"
  ],
  "Comida": [
    "Tacos al pastor", "Pozole", "Tamales", "Chilaquiles", "Mole poblano",
    "Chiles en nogada", "Birria", "Tlayuda", "Gorditas", "Elote con mayonesa",
    "Esquites", "Enchiladas", "Tostadas", "Quesadilla", "Cochinita pibil",
    "Sopes", "Menudo", "Carnitas", "Barbacoa", "Guacamole",
    "Pizza napolitana", "Sushi", "Ramen", "Hamburguesa", "Pad Thai",
    "Paella", "Croissant", "Fish and chips", "Pho", "Dim sum",
    "Kebab", "Falafel", "Ceviche", "Arepas", "Empanadas argentinas",
    "Poutine", "Currywurst", "Tikka masala", "Pasta carbonara", "Risotto",
    "Bibimbap", "Gyoza", "Bao", "Churros", "Crème brûlée",
    "Tiramisú", "Baklava", "Waffles belgas", "Panna cotta", "Macarons",
    "Big Mac", "Whopper", "KFC", "Domino's", "Pizza Hut",
    "Starbucks Frappuccino", "Subway", "Cheetos", "Doritos", "Oreo",
    "Nutella", "Coca-Cola", "Red Bull", "Maruchan", "Takis",
    "Brownie", "Cheesecake", "Paleta de hielo", "Helado napolitano", "Donas glaseadas",
    "Hot cakes", "Pan dulce", "Flan napolitano", "Tres leches", "Roles de canela",
    "Palomitas", "Papas fritas", "Nachos", "Hot dog", "Pretzel",
    "Michelada", "Horchata", "Agua de jamaica", "Margarita", "Sangría",
    "Mojito", "Piña colada", "Café americano", "Matcha latte", "Champagne"
  ],
  "Lugares": [
    "Torre Eiffel", "Machu Picchu", "Gran Muralla China", "Coliseo Romano", "Taj Mahal",
    "Pirámides de Giza", "Chichén Itzá", "Cristo Redentor", "Petra", "Angkor Wat",
    "Stonehenge", "Acrópolis de Atenas", "Estatua de la Libertad", "Big Ben", "Sagrada Familia",
    "Monte Rushmore", "Moái de Isla de Pascua", "Alhambra", "Kremlin", "Teotihuacán",
    "Tokio", "Nueva York", "París", "Londres", "Dubái",
    "Ciudad de México", "Estambul", "Río de Janeiro", "Sídney", "Roma",
    "Barcelona", "Ámsterdam", "Bangkok", "Seúl", "Praga",
    "La Habana", "Venecia", "Singapur", "Hong Kong", "Marrakech",
    "Gran Cañón", "Cataratas del Niágara", "Monte Everest", "Amazonas", "Galápagos",
    "Aurora boreal", "Gran Barrera de Coral", "Sahara", "Antártida", "Yellowstone",
    "Volcán Popocatépetl", "Selva Lacandona", "Cenotes de Yucatán", "Salto Ángel", "Fiordos de Noruega",
    "Monte Fuji", "Kilimanjaro", "Lago Titicaca", "Parque Yellowstone", "Desierto de Atacama",
    "Times Square", "Hollywood", "Las Vegas Strip", "Wall Street", "Silicon Valley",
    "Oxford Street", "Shibuya Crossing", "La Rambla", "Champs-Élysées", "Fifth Avenue",
    "Japón", "Italia", "Egipto", "Australia", "Brasil",
    "Alemania", "Grecia", "Islandia", "Tailandia", "Marruecos",
    "Noruega", "Nueva Zelanda", "Canadá", "Sudáfrica", "India"
  ],
  "Musica": [
    "Coldplay", "Queen", "The Beatles", "Pink Floyd", "Nirvana",
    "Radiohead", "Led Zeppelin", "AC/DC", "Metallica", "Guns N' Roses",
    "The Rolling Stones", "Red Hot Chili Peppers", "Arctic Monkeys", "Imagine Dragons", "Linkin Park",
    "Bad Bunny", "Peso Pluma", "Shakira", "J Balvin", "Daddy Yankee",
    "Karol G", "Rosalía", "Ozuna", "Maluma", "Rauw Alejandro",
    "Taylor Swift", "Billie Eilish", "Drake", "Kanye West", "Rihanna",
    "The Weeknd", "Dua Lipa", "Ariana Grande", "Beyoncé", "Adele",
    "Eminem", "Kendrick Lamar", "Travis Scott", "Post Malone", "Tyler the Creator",
    "Daft Punk", "Gorillaz", "Tame Impala", "The Strokes", "Oasis",
    "Maná", "Café Tacvba", "Molotov", "Zoé", "Los Tigres del Norte",
    "Vicente Fernández", "Juan Gabriel", "Luis Miguel", "José José", "Selena",
    "Caifanes", "Soda Stereo", "Gustavo Cerati", "Natalia Lafourcade", "Mon Laferte",
    "Bohemian Rhapsody", "Stairway to Heaven", "Hotel California", "Smells Like Teen Spirit", "Thriller",
    "Despacito", "Gasolina", "La Bamba", "Cielito Lindo", "Yellow",
    "Fix You", "Creep", "Somebody That I Used to Know", "Shape of You", "Blinding Lights",
    "Reggaetón", "Rock", "Hip-hop", "Corridos tumbados", "K-pop",
    "Jazz", "Blues", "Heavy metal", "Cumbia", "Ranchera",
    "Coachella", "Vive Latino", "Lollapalooza", "Glastonbury", "Grammy",
    "MTV", "Spotify", "Vinyl", "Unplugged", "Concierto"
  ],
  "Videojuegos": [
    "Fortnite", "Call of Duty Warzone", "Apex Legends", "PUBG", "Valorant",
    "Counter-Strike 2", "Overwatch 2", "Rainbow Six Siege", "Halo Infinite", "Destiny 2",
    "Call of Duty Modern Warfare", "Battlefield", "Splatoon", "Team Fortress 2", "Escape from Tarkov",
    "The Legend of Zelda Tears of the Kingdom", "Elden Ring", "Skyrim", "The Witcher 3", "Dark Souls",
    "God of War Ragnarök", "Baldur's Gate 3", "Final Fantasy VII", "Persona 5", "Cyberpunk 2077",
    "Horizon Zero Dawn", "Ghost of Tsushima", "Red Dead Redemption 2", "Mass Effect", "Dragon Age",
    "Minecraft", "Terraria", "Roblox", "Rust", "Subnautica",
    "No Man's Sky", "Valheim", "ARK Survival Evolved", "Don't Starve", "Palworld",
    "FIFA", "NBA 2K", "Rocket League", "Mario Kart", "Need for Speed",
    "Gran Turismo", "Forza Horizon", "Wii Sports", "F1", "Madden NFL",
    "Super Smash Bros", "Mortal Kombat", "Street Fighter", "Tekken", "Dragon Ball FighterZ",
    "Resident Evil 4", "Silent Hill 2", "Outlast", "Phasmophobia", "Five Nights at Freddy's",
    "Dead by Daylight", "Amnesia", "Alien Isolation", "Until Dawn", "Lethal Company",
    "Among Us", "Fall Guys", "Stardew Valley", "Hollow Knight", "Celeste",
    "Undertale", "Hades", "Cuphead", "It Takes Two", "Unpacking",
    "Super Mario Bros", "Pokémon", "Animal Crossing", "Kirby", "Metroid",
    "Donkey Kong", "Luigi's Mansion", "Fire Emblem", "Pikmin", "Splatoon",
    "GTA V", "The Last of Us", "Uncharted", "Spider-Man", "Assassin's Creed",
    "Bioshock", "Portal", "Half-Life", "Metal Gear Solid", "Devil May Cry"
  ],
  "Ciencia y Tecnologia": [
    "Albert Einstein", "Isaac Newton", "Nikola Tesla", "Marie Curie", "Stephen Hawking",
    "Charles Darwin", "Galileo Galilei", "Alan Turing", "Carl Sagan", "Neil deGrasse Tyson",
    "Leonardo da Vinci", "Arquímedes", "Richard Feynman", "Ada Lovelace", "Rosalind Franklin",
    "Apple", "Google", "Tesla", "SpaceX", "Microsoft",
    "Amazon", "Meta", "Netflix", "OpenAI", "NVIDIA",
    "Samsung", "Intel", "IBM", "Adobe", "Spotify",
    "iPhone", "ChatGPT", "YouTube", "TikTok", "Instagram",
    "WhatsApp", "Twitter", "PlayStation", "Xbox", "Nintendo Switch",
    "Windows", "MacBook", "AirPods", "Alexa", "Google Maps",
    "Wikipedia", "Zoom", "Discord", "Reddit", "Twitch",
    "Elon Musk", "Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Jeff Bezos",
    "Sam Altman", "Jensen Huang", "Tim Cook", "Satya Nadella", "Linus Torvalds",
    "Inteligencia artificial", "Agujero negro", "ADN", "Internet", "Blockchain",
    "Realidad virtual", "Robot", "Cohete espacial", "Satélite", "Estación Espacial Internacional",
    "Telescopio James Webb", "CERN", "Bosón de Higgs", "Energía nuclear", "Clon",
    "Impresión 3D", "Dron", "Coche autónomo", "Nanotecnología", "Computadora cuántica",
    "Mars Rover", "Voyager", "Hubble", "GPS", "WiFi"
  ],
  "Series y TV": [
    "Breaking Bad", "Game of Thrones", "The Sopranos", "Stranger Things", "The Walking Dead",
    "Better Call Saul", "House of the Dragon", "Peaky Blinders", "Narcos", "Ozark",
    "The Last of Us", "Succession", "True Detective", "Dexter", "Lost",
    "The Wire", "Mr. Robot", "Black Mirror", "Dark", "La Casa de Papel",
    "Élite", "Squid Game", "Wednesday", "The Bear", "Severance",
    "The Office", "Friends", "Brooklyn Nine-Nine", "How I Met Your Mother", "The Big Bang Theory",
    "Seinfeld", "Parks and Recreation", "Modern Family", "Arrested Development", "Schitt's Creek",
    "Ted Lasso", "Community", "The Good Place", "It's Always Sunny in Philadelphia", "Curb Your Enthusiasm",
    "Los Simpson", "Rick and Morty", "South Park", "Bob Esponja", "Dragon Ball Z",
    "Futurama", "Hora de Aventura", "Avatar La Leyenda de Aang", "Arcane", "Demon Slayer",
    "Attack on Titan", "One Piece", "Death Note", "Naruto", "Jujutsu Kaisen",
    "Evangelion", "Fullmetal Alchemist", "My Hero Academia", "Hunter x Hunter", "Chainsaw Man",
    "MasterChef", "Survivor", "The Amazing Race", "RuPaul's Drag Race", "Shark Tank",
    "Walter White", "Jon Snow", "Michael Scott", "Eleven", "Daryl Dixon",
    "Pablo Escobar", "Tommy Shelby", "Profesor", "Saul Goodman", "Tyrion Lannister"
  ],
  "Superheroes y Ficcion": [
    "Spider-Man", "Iron Man", "Thor", "Hulk", "Capitán América",
    "Black Panther", "Doctor Strange", "Wolverine", "Deadpool", "Thanos",
    "Loki", "Scarlet Witch", "Black Widow", "Ant-Man", "Groot",
    "Venom", "Nick Fury", "Gamora", "Star-Lord", "Vision",
    "Batman", "Superman", "Wonder Woman", "Aquaman", "Flash",
    "Joker", "Harley Quinn", "Green Lantern", "Cyborg", "Lex Luthor",
    "Catwoman", "Robin", "Nightwing", "Bane", "Darkseid",
    "Harry Potter", "Gandalf", "Darth Vader", "Yoda", "Luke Skywalker",
    "Princess Leia", "Han Solo", "Gollum", "Aragorn", "Frodo",
    "Katniss Everdeen", "Jack Sparrow", "Indiana Jones", "James Bond", "John Wick",
    "Neo", "Morpheus", "Optimus Prime", "Goku", "Naruto Uzumaki",
    "Luffy", "Pikachu", "Mario", "Link", "Sonic",
    "Shrek", "Buzz Lightyear", "Elsa", "Simba", "Woody",
    "Magneto", "Doctor Doom", "Ultron", "Voldemort", "Sauron",
    "Pennywise", "Freddy Krueger", "Jason Voorhees", "Hannibal Lecter", "Xenomorfo",
    "T-1000", "Agent Smith", "Palpatine", "Freezer", "Megatron"
  ],
  "Marcas y Empresas": [
    "McDonald's", "Burger King", "KFC", "Starbucks", "Subway",
    "Domino's", "Pizza Hut", "Taco Bell", "Chick-fil-A", "Wendy's",
    "Oxxo", "7-Eleven", "Costco", "Walmart", "Liverpool",
    "Nike", "Adidas", "Zara", "H&M", "Gucci",
    "Louis Vuitton", "Supreme", "Puma", "Converse", "Vans",
    "Levi's", "Balenciaga", "Ralph Lauren", "New Balance", "Jordan",
    "Ferrari", "Lamborghini", "Tesla", "BMW", "Mercedes-Benz",
    "Porsche", "Audi", "Toyota", "Ford", "Chevrolet",
    "Bugatti", "Rolls-Royce", "Mustang", "Corvette", "Jeep",
    "Apple", "Samsung", "Sony", "Nintendo", "Xbox",
    "Google", "Amazon", "Netflix", "Spotify", "TikTok",
    "Coca-Cola", "Pepsi", "Red Bull", "Gatorade", "Monster Energy",
    "Corona", "Heineken", "Jack Daniel's", "Don Julio", "Modelo",
    "Disney", "LEGO", "IKEA", "Rolex", "Ray-Ban",
    "GoPro", "Canon", "Shein", "Mercado Libre", "Uber",
    "Airbnb", "Rappi", "Duolingo", "HBO Max", "YouTube"
  ],
  "Historia y Cultura": [
    "Cleopatra", "Julio César", "Napoleón", "Genghis Khan", "Alejandro Magno",
    "Tutankamón", "Cristóbal Colón", "Marco Polo", "Simón Bolívar", "Pancho Villa",
    "Emiliano Zapata", "Benito Juárez", "Frida Kahlo", "Diego Rivera", "Sor Juana Inés de la Cruz",
    "Abraham Lincoln", "Martin Luther King", "Gandhi", "Nelson Mandela", "Che Guevara",
    "Winston Churchill", "Juana de Arco", "Leonardo da Vinci", "Miguel Ángel", "Shakespeare",
    "Aztecas", "Mayas", "Incas", "Egipto antiguo", "Imperio Romano",
    "Vikingos", "Samurái", "Espartanos", "Gladiadores", "Faraón",
    "Piratas del Caribe", "Caballeros templarios", "Ninjas", "Conquista de México", "Revolución Francesa",
    "Segunda Guerra Mundial", "Caída del Muro de Berlín", "Llegada a la Luna", "Titanic", "Revolución Mexicana",
    "Independencia de México", "Guerra Fría", "Descubrimiento de América", "Renacimiento", "Edad Media",
    "Mona Lisa", "La Noche Estrellada", "El Grito", "David de Miguel Ángel", "La Última Cena",
    "Las Dos Fridas", "Guernica", "La Persistencia de la Memoria", "El Pensador", "Venus de Milo",
    "Zeus", "Poseidón", "Hades", "Quetzalcóatl", "Thor mitológico",
    "Medusa", "Minotauro", "Pegaso", "Fénix", "Dragón",
    "Hércules", "Aquiles", "Odiseo", "Anubis", "Valkiria"
  ],
  "Otros Deportes": [
    "Michael Jordan", "LeBron James", "Kobe Bryant", "Stephen Curry", "Shaquille O'Neal",
    "Magic Johnson", "Larry Bird", "Kevin Durant", "Giannis Antetokounmpo", "Luka Dončić",
    "Los Angeles Lakers", "Chicago Bulls", "Golden State Warriors", "Boston Celtics", "Miami Heat",
    "Roger Federer", "Rafael Nadal", "Novak Djokovic", "Serena Williams", "Carlos Alcaraz",
    "Wimbledon", "Roland Garros", "US Open", "Australian Open",
    "Muhammad Ali", "Mike Tyson", "Floyd Mayweather", "Canelo Álvarez", "Manny Pacquiao",
    "Conor McGregor", "Khabib Nurmagomedov", "UFC", "Jon Jones", "Israel Adesanya",
    "Max Verstappen", "Lewis Hamilton", "Checo Pérez", "Ayrton Senna", "Michael Schumacher",
    "Charles Leclerc", "Fernando Alonso", "Red Bull Racing", "Ferrari F1", "Mercedes F1",
    "Usain Bolt", "Simone Biles", "Michael Phelps", "Tiger Woods", "Nadia Comăneci",
    "Olympics", "Tour de France", "WWE", "Wrestlemania", "The Undertaker",
    "John Cena", "The Rock", "Skateboard", "Surf", "Snowboard",
    "NBA Slam Dunk Contest", "March Madness", "Champions League Final", "Super Bowl Halftime", "Copa Davis"
  ]
};

export const CATEGORY_EMOJIS: Record<string, string> = {
  "Futbol": "⚽",
  "Futbol Americano": "🏈",
  "Cine": "🎬",
  "Animales": "🐾",
  "Comida": "🍕",
  "Lugares": "📍",
  "Musica": "🎵",
  "Videojuegos": "🎮",
  "Ciencia y Tecnologia": "🔬",
  "Series y TV": "📺",
  "Superheroes y Ficcion": "🦸",
  "Marcas y Empresas": "🏷️",
  "Historia y Cultura": "🌍",
  "Otros Deportes": "🏀"
};

export const ALL_CATEGORIES = Object.keys(WORD_BANK);
